apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
   nodePort: 32090  # Set a NodePort (e.g., 32090)
  type: NodePort  # Changed from LoadBalancer to NodePort
