apiVersion: v1
kind: Service
metadata:
  name: zta-service
spec:
  selector:
    app: zta
  ports:
    - protocol: TCP
      port: 80           # External Port (For Clients)
      targetPort: 5000    # Must match containerPort
      nodePort: 30000     # Minikube Exposed Port
  type: NodePort  # Ensure it's NodePort, not LoadBalancer
