replicaCount: 5

image:
  repository: skfditiss/zta # Replace with your actual DockerHub username
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 5000
  nodePort: 30000
  type: NodePort


resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"
